// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANYgpPxx82HKD8I3S-tayrYP-IVAZC6qU',
    appId: '1:1082814269313:web:b9bd2ed1215219ab68ca80',
    messagingSenderId: '1082814269313',
    projectId: 'medlink-aa15b',
    authDomain: 'medlink-aa15b.firebaseapp.com',
    storageBucket: 'medlink-aa15b.appspot.com',
    measurementId: 'G-4GE1J678QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLVmi21ukCxRuWCjDR_AoquYd0I9XgKwo',
    appId: '1:1082814269313:android:e58ded0719cdd5f568ca80',
    messagingSenderId: '1082814269313',
    projectId: 'medlink-aa15b',
    storageBucket: 'medlink-aa15b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA81mO1mOe7gchSymgy3V6RN3YbM1qMWzk',
    appId: '1:1082814269313:ios:db67cf412ee24b3468ca80',
    messagingSenderId: '1082814269313',
    projectId: 'medlink-aa15b',
    storageBucket: 'medlink-aa15b.appspot.com',
    androidClientId: '1082814269313-169r9tugh0ndqdieu08ih9fg394ma9o9.apps.googleusercontent.com',
    iosClientId: '1082814269313-86okftbnbmputfv34uaf8mjoohdjib29.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANYgpPxx82HKD8I3S-tayrYP-IVAZC6qU',
    appId: '1:1082814269313:web:40c7abd4385579fb68ca80',
    messagingSenderId: '1082814269313',
    projectId: 'medlink-aa15b',
    authDomain: 'medlink-aa15b.firebaseapp.com',
    storageBucket: 'medlink-aa15b.appspot.com',
    measurementId: 'G-T6NZHWLP1N',
  );

}